#include "Param.h"

#include <boost/property_tree/xml_parser.hpp>
#include <iostream>
#include <string>
#include <math.h>

namespace pt = boost::property_tree;
namespace CancerVCT{
using std::string;
using std::vector;

#define PARAM_DESCRIPTION_FIELD_COUNT 3
const char* _description[][PARAM_DESCRIPTION_FIELD_COUNT] =
{
    //simulation settings
    {"Param.QSP.simulation.start","",""},//0
    {"Param.QSP.simulation.step","",""},//1
    {"Param.QSP.simulation.n_step","",""},//2
    {"Param.QSP.simulation.tol_rel","",""},//3
    {"Param.QSP.simulation.tol_abs","",""},//4
    //compartments
    {"Param.QSP.init_value.Compartment.V_C","",""},//5|5
    {"Param.QSP.init_value.Compartment.V_P","",""},//6|6
    {"Param.QSP.init_value.Compartment.V_T","",""},//7|7
    {"Param.QSP.init_value.Compartment.V_LN","",""},//8|8
    {"Param.QSP.init_value.Compartment.V_e","",""},//9|9
    {"Param.QSP.init_value.Compartment.A_e","",""},//10|10
    {"Param.QSP.init_value.Compartment.A_s","",""},//11|11
    {"Param.QSP.init_value.Compartment.syn_CT","",""},//12|12
    {"Param.QSP.init_value.Compartment.syn_DN","",""},//13|13
    {"Param.QSP.init_value.Compartment.Treg_P","",""},//14|14
    {"Param.QSP.init_value.Compartment.Treg_T","",""},//15|15
    //species
    {"Param.QSP.init_value.Species.V_C_nT1","",""},//16|16
    {"Param.QSP.init_value.Species.V_C_T1","",""},//17|17
    {"Param.QSP.init_value.Species.V_C_nT0","",""},//18|18
    {"Param.QSP.init_value.Species.V_C_T0","",""},//19|19
    {"Param.QSP.init_value.Species.V_C_nivolumab","",""},//20|20
    {"Param.QSP.init_value.Species.V_C_cabozantinib","",""},//21|21
    {"Param.QSP.init_value.Species.V_C_A_site1","",""},//22|22
    {"Param.QSP.init_value.Species.V_C_A_site2","",""},//23|23
    {"Param.QSP.init_value.Species.V_P_nT1","",""},//24|24
    {"Param.QSP.init_value.Species.V_P_T1","",""},//25|25
    {"Param.QSP.init_value.Species.V_P_nT0","",""},//26|26
    {"Param.QSP.init_value.Species.V_P_T0","",""},//27|27
    {"Param.QSP.init_value.Species.V_P_nivolumab","",""},//28|28
    {"Param.QSP.init_value.Species.V_P_cabozantinib","",""},//29|29
    {"Param.QSP.init_value.Species.V_T_C_x","",""},//30|30
    {"Param.QSP.init_value.Species.V_T_T_exh","",""},//31|31
    {"Param.QSP.init_value.Species.V_T_C1","",""},//32|32
    {"Param.QSP.init_value.Species.V_T_T1","",""},//33|33
    {"Param.QSP.init_value.Species.V_T_T0","",""},//34|34
    {"Param.QSP.init_value.Species.V_T_APC","",""},//35|35
    {"Param.QSP.init_value.Species.V_T_mAPC","",""},//36|36
    {"Param.QSP.init_value.Species.V_T_c","",""},//37|37
    {"Param.QSP.init_value.Species.V_T_P0","",""},//38|38
    {"Param.QSP.init_value.Species.V_T_P1","",""},//39|39
    {"Param.QSP.init_value.Species.V_T_nivolumab","",""},//40|40
    {"Param.QSP.init_value.Species.V_T_cabozantinib","",""},//41|41
    {"Param.QSP.init_value.Species.V_T_v_cabo","",""},//42|42
    {"Param.QSP.init_value.Species.V_LN_nT1","",""},//43|43
    {"Param.QSP.init_value.Species.V_LN_aT1","",""},//44|44
    {"Param.QSP.init_value.Species.V_LN_T1","",""},//45|45
    {"Param.QSP.init_value.Species.V_LN_IL2","",""},//46|46
    {"Param.QSP.init_value.Species.V_LN_nT0","",""},//47|47
    {"Param.QSP.init_value.Species.V_LN_aT0","",""},//48|48
    {"Param.QSP.init_value.Species.V_LN_T0","",""},//49|49
    {"Param.QSP.init_value.Species.V_LN_APC","",""},//50|50
    {"Param.QSP.init_value.Species.V_LN_mAPC","",""},//51|51
    {"Param.QSP.init_value.Species.V_LN_nivolumab","",""},//52|52
    {"Param.QSP.init_value.Species.V_LN_cabozantinib","",""},//53|53
    {"Param.QSP.init_value.Species.V_e_P0","",""},//54|54
    {"Param.QSP.init_value.Species.V_e_p0","",""},//55|55
    {"Param.QSP.init_value.Species.V_e_P1","",""},//56|56
    {"Param.QSP.init_value.Species.V_e_p1","",""},//57|57
    {"Param.QSP.init_value.Species.A_e_M1","",""},//58|58
    {"Param.QSP.init_value.Species.A_e_M1p0","",""},//59|59
    {"Param.QSP.init_value.Species.A_e_M1p1","",""},//60|60
    {"Param.QSP.init_value.Species.A_s_M1","",""},//61|61
    {"Param.QSP.init_value.Species.A_s_M1p0","",""},//62|62
    {"Param.QSP.init_value.Species.A_s_M1p1","",""},//63|63
    {"Param.QSP.init_value.Species.syn_CT_PD1_PDL1","",""},//64|64
    {"Param.QSP.init_value.Species.syn_CT_PD1_PDL2","",""},//65|65
    {"Param.QSP.init_value.Species.syn_CT_PD1_aPD1","",""},//66|66
    {"Param.QSP.init_value.Species.syn_CT_PD1_aPD1_PD1","",""},//67|67
    {"Param.QSP.init_value.Species.syn_CT_PDL1_aPDL1","",""},//68|68
    {"Param.QSP.init_value.Species.syn_CT_PDL1_aPDL1_PDL1","",""},//69|69
    {"Param.QSP.init_value.Species.syn_DN_CD28_CD80","",""},//70|70
    {"Param.QSP.init_value.Species.syn_DN_CD28_CD80_CD28","",""},//71|71
    {"Param.QSP.init_value.Species.syn_DN_CD28_CD86","",""},//72|72
    {"Param.QSP.init_value.Species.syn_DN_PDL1_CD80","",""},//73|73
    {"Param.QSP.init_value.Species.syn_DN_CTLA4_CD80","",""},//74|74
    {"Param.QSP.init_value.Species.syn_DN_CTLA4_CD80_CTLA4","",""},//75|75
    {"Param.QSP.init_value.Species.syn_DN_CD80_CTLA4_CD80","",""},//76|76
    {"Param.QSP.init_value.Species.syn_DN_CTLA4_CD80_CTLA4_CD80","",""},//77|77
    {"Param.QSP.init_value.Species.syn_DN_CTLA4_CD86","",""},//78|78
    {"Param.QSP.init_value.Species.syn_DN_CD86_CTLA4_CD86","",""},//79|79
    {"Param.QSP.init_value.Species.syn_DN_CTLA4_aCTLA4","",""},//80|80
    {"Param.QSP.init_value.Species.syn_DN_CTLA4_aCTLA4_CTLA4","",""},//81|81
    {"Param.QSP.init_value.Species.syn_DN_PDL1_aPDL1","",""},//82|82
    {"Param.QSP.init_value.Species.syn_DN_PDL1_aPDL1_PDL1","",""},//83|83
    {"Param.QSP.init_value.Species.Treg_P_CTLA4_aCTLA4","",""},//84|84
    {"Param.QSP.init_value.Species.Treg_P_CTLA4_aCTLA4_CTLA4","",""},//85|85
    {"Param.QSP.init_value.Species.Treg_T_CTLA4_aCTLA4","",""},//86|86
    {"Param.QSP.init_value.Species.Treg_T_CTLA4_aCTLA4_CTLA4","",""},//87|87
    //parameters
    {"Param.QSP.init_value.Parameter.k_cell_clear","",""},//88|88
    {"Param.QSP.init_value.Parameter.cell","",""},//89|89
    {"Param.QSP.init_value.Parameter.day","",""},//90|90
    {"Param.QSP.init_value.Parameter.cellmcm2","",""},//91|91
    {"Param.QSP.init_value.Parameter.molarity","",""},//92|92
    {"Param.QSP.init_value.Parameter.vol_cell","",""},//93|93
    {"Param.QSP.init_value.Parameter.vol_Tcell","",""},//94|94
    {"Param.QSP.init_value.Parameter.V_Tmin","",""},//95|95
    {"Param.QSP.init_value.Parameter.C_total","",""},//96|96
    {"Param.QSP.init_value.Parameter.R_Tcell","",""},//97|97
    {"Param.QSP.init_value.Parameter.T_C","",""},//98|98
    {"Param.QSP.init_value.Parameter.T_P","",""},//99|99
    {"Param.QSP.init_value.Parameter.T_T","",""},//100|100
    {"Param.QSP.init_value.Parameter.T_LN","",""},//101|101
    {"Param.QSP.init_value.Parameter.Tregs_C","",""},//102|102
    {"Param.QSP.init_value.Parameter.Tregs_P","",""},//103|103
    {"Param.QSP.init_value.Parameter.Tregs_T","",""},//104|104
    {"Param.QSP.init_value.Parameter.Tregs_LN","",""},//105|105
    {"Param.QSP.init_value.Parameter.APC_LN","",""},//106|106
    {"Param.QSP.init_value.Parameter.mAPC_LN","",""},//107|107
    {"Param.QSP.init_value.Parameter.blood_volume","",""},//108|108
    {"Param.QSP.init_value.Parameter.peripheral_volume","",""},//109|109
    {"Param.QSP.init_value.Parameter.LN_volume","",""},//110|110
    {"Param.QSP.init_value.Parameter.H_PD1","",""},//111|111
    {"Param.QSP.init_value.Parameter.H_CD28","",""},//112|112
    {"Param.QSP.init_value.Parameter.k_C1_growth","",""},//113|113
    {"Param.QSP.init_value.Parameter.C_max","",""},//114|114
    {"Param.QSP.init_value.Parameter.k_C1_death","",""},//115|115
    {"Param.QSP.init_value.Parameter.initial_tumour_diameter","",""},//116|116
    {"Param.QSP.init_value.Parameter.div_T1","",""},//117|117
    {"Param.QSP.init_value.Parameter.n_T1_clones","",""},//118|118
    {"Param.QSP.init_value.Parameter.q_T1_LN_in","",""},//119|119
    {"Param.QSP.init_value.Parameter.q_T1_LN_out","",""},//120|120
    {"Param.QSP.init_value.Parameter.k_T1_act","",""},//121|121
    {"Param.QSP.init_value.Parameter.k_T1_pro","",""},//122|122
    {"Param.QSP.init_value.Parameter.k_T1_death","",""},//123|123
    {"Param.QSP.init_value.Parameter.q_T1_P_in","",""},//124|124
    {"Param.QSP.init_value.Parameter.q_T1_P_out","",""},//125|125
    {"Param.QSP.init_value.Parameter.q_T1_T_in","",""},//126|126
    {"Param.QSP.init_value.Parameter.Q_nT1_thym","",""},//127|127
    {"Param.QSP.init_value.Parameter.k_nT1_pro","",""},//128|128
    {"Param.QSP.init_value.Parameter.K_nT1_pro","",""},//129|129
    {"Param.QSP.init_value.Parameter.k_nT1_death","",""},//130|130
    {"Param.QSP.init_value.Parameter.k_IL2_deg","",""},//131|131
    {"Param.QSP.init_value.Parameter.k_IL2_cons","",""},//132|132
    {"Param.QSP.init_value.Parameter.k_IL2_sec","",""},//133|133
    {"Param.QSP.init_value.Parameter.IL2_50","",""},//134|134
    {"Param.QSP.init_value.Parameter.N0","",""},//135|135
    {"Param.QSP.init_value.Parameter.N_IL2","",""},//136|136
    {"Param.QSP.init_value.Parameter.k_T1","",""},//137|137
    {"Param.QSP.init_value.Parameter.k_C_T1","",""},//138|138
    {"Param.QSP.init_value.Parameter.k_Treg","",""},//139|139
    {"Param.QSP.init_value.Parameter.H_act1","",""},//140|140
    {"Param.QSP.init_value.Parameter.H_P1","",""},//141|141
    {"Param.QSP.init_value.Parameter.N_aT","",""},//142|142
    {"Param.QSP.init_value.Parameter.div_T0","",""},//143|143
    {"Param.QSP.init_value.Parameter.n_T0_clones","",""},//144|144
    {"Param.QSP.init_value.Parameter.q_T0_LN_in","",""},//145|145
    {"Param.QSP.init_value.Parameter.q_T0_LN_out","",""},//146|146
    {"Param.QSP.init_value.Parameter.k_T0_act","",""},//147|147
    {"Param.QSP.init_value.Parameter.k_T0_pro","",""},//148|148
    {"Param.QSP.init_value.Parameter.k_T0_death","",""},//149|149
    {"Param.QSP.init_value.Parameter.q_T0_P_in","",""},//150|150
    {"Param.QSP.init_value.Parameter.q_T0_P_out","",""},//151|151
    {"Param.QSP.init_value.Parameter.q_T0_T_in","",""},//152|152
    {"Param.QSP.init_value.Parameter.Q_nT0_thym","",""},//153|153
    {"Param.QSP.init_value.Parameter.k_nT0_pro","",""},//154|154
    {"Param.QSP.init_value.Parameter.K_nT0_pro","",""},//155|155
    {"Param.QSP.init_value.Parameter.k_nT0_death","",""},//156|156
    {"Param.QSP.init_value.Parameter.H_act0","",""},//157|157
    {"Param.QSP.init_value.Parameter.H_P0","",""},//158|158
    {"Param.QSP.init_value.Parameter.k_APC_mat","",""},//159|159
    {"Param.QSP.init_value.Parameter.k_APC_mig","",""},//160|160
    {"Param.QSP.init_value.Parameter.k_APC_death","",""},//161|161
    {"Param.QSP.init_value.Parameter.k_mAPC_death","",""},//162|162
    {"Param.QSP.init_value.Parameter.APC0_T","",""},//163|163
    {"Param.QSP.init_value.Parameter.APC0_LN","",""},//164|164
    {"Param.QSP.init_value.Parameter.k_c","",""},//165|165
    {"Param.QSP.init_value.Parameter.c0","",""},//166|166
    {"Param.QSP.init_value.Parameter.c50","",""},//167|167
    {"Param.QSP.init_value.Parameter.DAMPs","",""},//168|168
    {"Param.QSP.init_value.Parameter.n_sites_APC","",""},//169|169
    {"Param.QSP.init_value.Parameter.kin","",""},//170|170
    {"Param.QSP.init_value.Parameter.kout","",""},//171|171
    {"Param.QSP.init_value.Parameter.k_P0_up","",""},//172|172
    {"Param.QSP.init_value.Parameter.k_xP0_deg","",""},//173|173
    {"Param.QSP.init_value.Parameter.k_P0_deg","",""},//174|174
    {"Param.QSP.init_value.Parameter.k_p0_deg","",""},//175|175
    {"Param.QSP.init_value.Parameter.k_P0_on","",""},//176|176
    {"Param.QSP.init_value.Parameter.k_P0_d1","",""},//177|177
    {"Param.QSP.init_value.Parameter.p0_50","",""},//178|178
    {"Param.QSP.init_value.Parameter.P0_C1","",""},//179|179
    {"Param.QSP.init_value.Parameter.A_syn","",""},//180|180
    {"Param.QSP.init_value.Parameter.A_Tcell","",""},//181|181
    {"Param.QSP.init_value.Parameter.A_cell","",""},//182|182
    {"Param.QSP.init_value.Parameter.k_M1p0_TCR_on","",""},//183|183
    {"Param.QSP.init_value.Parameter.k_M1p0_TCR_off","",""},//184|184
    {"Param.QSP.init_value.Parameter.TCR_p0_tot","",""},//185|185
    {"Param.QSP.init_value.Parameter.pTCR_p0_MHC_tot","",""},//186|186
    {"Param.QSP.init_value.Parameter.k_P1_up","",""},//187|187
    {"Param.QSP.init_value.Parameter.k_xP1_deg","",""},//188|188
    {"Param.QSP.init_value.Parameter.k_P1_deg","",""},//189|189
    {"Param.QSP.init_value.Parameter.k_p1_deg","",""},//190|190
    {"Param.QSP.init_value.Parameter.k_P1_on","",""},//191|191
    {"Param.QSP.init_value.Parameter.k_P1_d1","",""},//192|192
    {"Param.QSP.init_value.Parameter.p1_50","",""},//193|193
    {"Param.QSP.init_value.Parameter.P1_C1","",""},//194|194
    {"Param.QSP.init_value.Parameter.k_M1p1_TCR_on","",""},//195|195
    {"Param.QSP.init_value.Parameter.k_M1p1_TCR_off","",""},//196|196
    {"Param.QSP.init_value.Parameter.k_M1p1_TCR_p","",""},//197|197
    {"Param.QSP.init_value.Parameter.phi_M1p1_TCR","",""},//198|198
    {"Param.QSP.init_value.Parameter.N_M1p1_TCR","",""},//199|199
    {"Param.QSP.init_value.Parameter.TCR_p1_tot","",""},//200|200
    {"Param.QSP.init_value.Parameter.pTCR_p1_MHC_tot","",""},//201|201
    {"Param.QSP.init_value.Parameter.q_P_nivolumab","",""},//202|202
    {"Param.QSP.init_value.Parameter.q_T_nivolumab","",""},//203|203
    {"Param.QSP.init_value.Parameter.q_LN_nivolumab","",""},//204|204
    {"Param.QSP.init_value.Parameter.q_LD_nivolumab","",""},//205|205
    {"Param.QSP.init_value.Parameter.k_cl_nivolumab","",""},//206|206
    {"Param.QSP.init_value.Parameter.gamma_C_nivolumab","",""},//207|207
    {"Param.QSP.init_value.Parameter.gamma_P_nivolumab","",""},//208|208
    {"Param.QSP.init_value.Parameter.gamma_T_nivolumab","",""},//209|209
    {"Param.QSP.init_value.Parameter.gamma_LN_nivolumab","",""},//210|210
    {"Param.QSP.init_value.Parameter.T_PD1_total","",""},//211|211
    {"Param.QSP.init_value.Parameter.C_PDL1_total","",""},//212|212
    {"Param.QSP.init_value.Parameter.C_PDL2_total","",""},//213|213
    {"Param.QSP.init_value.Parameter.A_CD80_total","",""},//214|214
    {"Param.QSP.init_value.Parameter.A_CD86_total","",""},//215|215
    {"Param.QSP.init_value.Parameter.N_CD28_total","",""},//216|216
    {"Param.QSP.init_value.Parameter.N_PDL1_total","",""},//217|217
    {"Param.QSP.init_value.Parameter.N_CTLA4_total","",""},//218|218
    {"Param.QSP.init_value.Parameter.Treg_CTLA4_total","",""},//219|219
    {"Param.QSP.init_value.Parameter.kon_PD1_PDL1","",""},//220|220
    {"Param.QSP.init_value.Parameter.koff_PD1_PDL1","",""},//221|221
    {"Param.QSP.init_value.Parameter.kon_PD1_PDL2","",""},//222|222
    {"Param.QSP.init_value.Parameter.koff_PD1_PDL2","",""},//223|223
    {"Param.QSP.init_value.Parameter.kon_CD28_CD80","",""},//224|224
    {"Param.QSP.init_value.Parameter.koff_CD28_CD80","",""},//225|225
    {"Param.QSP.init_value.Parameter.kon_CD28_CD86","",""},//226|226
    {"Param.QSP.init_value.Parameter.koff_CD28_CD86","",""},//227|227
    {"Param.QSP.init_value.Parameter.kon_CTLA4_CD80","",""},//228|228
    {"Param.QSP.init_value.Parameter.koff_CTLA4_CD80","",""},//229|229
    {"Param.QSP.init_value.Parameter.kon_CTLA4_CD86","",""},//230|230
    {"Param.QSP.init_value.Parameter.koff_CTLA4_CD86","",""},//231|231
    {"Param.QSP.init_value.Parameter.kon_PDL1_CD80","",""},//232|232
    {"Param.QSP.init_value.Parameter.koff_PDL1_CD80","",""},//233|233
    {"Param.QSP.init_value.Parameter.kon_PD1_aPD1","",""},//234|234
    {"Param.QSP.init_value.Parameter.koff_PD1_aPD1","",""},//235|235
    {"Param.QSP.init_value.Parameter.Chi_PD1","",""},//236|236
    {"Param.QSP.init_value.Parameter.PD1_50","",""},//237|237
    {"Param.QSP.init_value.Parameter.n_PD1","",""},//238|238
    {"Param.QSP.init_value.Parameter.CD28_50","",""},//239|239
    {"Param.QSP.init_value.Parameter.n_CD28","",""},//240|240
    {"Param.QSP.init_value.Parameter.N_CD28","",""},//241|241
    {"Param.QSP.init_value.Parameter.CTLA4_50","",""},//242|242
    {"Param.QSP.init_value.Parameter.n_ADCC","",""},//243|243
    {"Param.QSP.init_value.Parameter.k_ADCC","",""},//244|244
    {"Param.QSP.init_value.Parameter.H_ADCC_P","",""},//245|245
    {"Param.QSP.init_value.Parameter.H_ADCC_T","",""},//246|246
    {"Param.QSP.init_value.Parameter.k_a1_cabozantinib","",""},//247|247
    {"Param.QSP.init_value.Parameter.k_a2_cabozantinib","",""},//248|248
    {"Param.QSP.init_value.Parameter.k_cln_cabozantinib","",""},//249|249
    {"Param.QSP.init_value.Parameter.Kc_cabozantinib","",""},//250|250
    {"Param.QSP.init_value.Parameter.lagP1_cabozantinib","",""},//251|251
    {"Param.QSP.init_value.Parameter.lagP2_cabozantinib","",""},//252|252
    {"Param.QSP.init_value.Parameter.F_cabozantinib","",""},//253|253
    {"Param.QSP.init_value.Parameter.q_P_cabozantinib","",""},//254|254
    {"Param.QSP.init_value.Parameter.q_T_cabozantinib","",""},//255|255
    {"Param.QSP.init_value.Parameter.q_LN_cabozantinib","",""},//256|256
    {"Param.QSP.init_value.Parameter.q_LD_cabozantinib","",""},//257|257
    {"Param.QSP.init_value.Parameter.gamma_C_cabozantinib","",""},//258|258
    {"Param.QSP.init_value.Parameter.gamma_P_cabozantinib","",""},//259|259
    {"Param.QSP.init_value.Parameter.gamma_T_cabozantinib","",""},//260|260
    {"Param.QSP.init_value.Parameter.gamma_LN_cabozantinib","",""},//261|261
    {"Param.QSP.init_value.Parameter.IC50_MET","",""},//262|262
    {"Param.QSP.init_value.Parameter.IC50_RET","",""},//263|263
    {"Param.QSP.init_value.Parameter.IC50_AXL","",""},//264|264
    {"Param.QSP.init_value.Parameter.IC50_VEGFR2","",""},//265|265
    {"Param.QSP.init_value.Parameter.cabo0","",""},//266|266
    {"Param.QSP.init_value.Parameter.kv_cabo","",""},//267|267
    {"Param.QSP.init_value.Parameter.kr_cabo","",""},//268|268
    {"Param.QSP.init_value.Parameter.lambda_C_cabo","",""},//269|269
    {"Param.QSP.init_value.Parameter.lambda_v_cabo","",""},//270|270
    {"Param.QSP.init_value.Parameter.lambda_q_cabo","",""},//271|271
    {"Param.QSP.init_value.Parameter.R_cabo","",""},//272|272
    {"Param.QSP.init_value.Parameter.frac","",""},//273|273
};

Param::Param()
    :ParamBase()
{
    setupParam();
}

void Param::setupParam(){
    for (size_t i = 0; i < 274; i++)
    {
        _paramDesc.push_back(vector<string>(_description[i], 
            _description[i]+ PARAM_DESCRIPTION_FIELD_COUNT));
    }
    _paramFloat = vector<double>(274, 0);
}

};
